// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { NonOwnableContract$Type } from "./NonOwnableContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NonOwnableContract"]: NonOwnableContract$Type;
    ["contracts/NonOwnableContract.sol:NonOwnableContract"]: NonOwnableContract$Type;
  }
}
