// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface NonOwnableContract$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "NonOwnableContract",
  "sourceName": "contracts/NonOwnableContract.sol",
  "abi": [
    {
      "inputs": [],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "inputs": [],
      "name": "returns100",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x608060405234801561001057600080fd5b50606460008190555060b3806100276000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80633fba859614602d575b600080fd5b60336047565b604051603e91906064565b60405180910390f35b60005481565b6000819050919050565b605e81604d565b82525050565b6000602082019050607760008301846057565b9291505056fea2646970667358221220ba5f79185c3dbbb6d296febc4607a81397838eb485d3690920c781ce96e379c464736f6c63430008130033",
  "deployedBytecode": "0x6080604052348015600f57600080fd5b506004361060285760003560e01c80633fba859614602d575b600080fd5b60336047565b604051603e91906064565b60405180910390f35b60005481565b6000819050919050565b605e81604d565b82525050565b6000602082019050607760008301846057565b9291505056fea2646970667358221220ba5f79185c3dbbb6d296febc4607a81397838eb485d3690920c781ce96e379c464736f6c63430008130033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "NonOwnableContract",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<NonOwnableContract$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/NonOwnableContract.sol:NonOwnableContract",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<NonOwnableContract$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "NonOwnableContract",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<NonOwnableContract$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/NonOwnableContract.sol:NonOwnableContract",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<NonOwnableContract$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "NonOwnableContract",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<NonOwnableContract$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/NonOwnableContract.sol:NonOwnableContract",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<NonOwnableContract$Type["abi"]>>;
}
