// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { OwnableContract$Type } from './OwnableContract';

declare module 'hardhat/types/artifacts' {
  interface ArtifactsMap {
    ['OwnableContract']: OwnableContract$Type;
    ['contracts/OwnableContract.sol:OwnableContract']: OwnableContract$Type;
  }
}
